### ISSUE TITLE
Examples of the solved tasks

### ISSUE THREAD

**Issue by zamazan4ik** [accetone/cwp#1]
Hello.

Thank you for the great work!

Can you please add examples of the solved tasks. Students will have chance to understand the right way for working with Javascript technology stack.

**Comment by accetone** [comment]
@ZaMaZaN4iK I'm afraid this is not possible. In that case anybody can say that he did the task without even look into the code. Anyway when students show me their solutions we discuss their code and the ways to improve it. Also there are a lot of popular open-source projects that you can look into like axios, bluebird or nodejs itself. If you need style guide you can take a look at https://github.com/airbnb/javascript. 

BTW we can communicate in Russian here. 

Regards,
Nikita

**Comment by zamazan4ik** [comment]
Ok, thank you for the brief answer.
